//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceUsuarioReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/Datos")]
    public partial class Usuarios : object
    {
        
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        private int IdField;
        
        private string NombreField;
        
        private string SexoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuarioReference.IUsuarios")]
    public interface IUsuarios
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetUsuarios", ReplyAction="http://tempuri.org/IUsuarios/GetUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceUsuarioReference.Usuarios>> GetUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetUsuario", ReplyAction="http://tempuri.org/IUsuarios/GetUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceUsuarioReference.Usuarios> GetUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/SetUsuario", ReplyAction="http://tempuri.org/IUsuarios/SetUsuarioResponse")]
        System.Threading.Tasks.Task<bool> SetUsuarioAsync(string Nombre, System.DateTime Nacimiento, string Sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/UpdateUsuario", ReplyAction="http://tempuri.org/IUsuarios/UpdateUsuarioResponse")]
        System.Threading.Tasks.Task<bool> UpdateUsuarioAsync(int id, string Nombre, System.DateTime Nacimiento, string Sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/RemoveUsuario", ReplyAction="http://tempuri.org/IUsuarios/RemoveUsuarioResponse")]
        System.Threading.Tasks.Task<bool> RemoveUsuarioAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IUsuariosChannel : ServiceUsuarioReference.IUsuarios, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<ServiceUsuarioReference.IUsuarios>, ServiceUsuarioReference.IUsuarios
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UsuariosClient() : 
                base(UsuariosClient.GetDefaultBinding(), UsuariosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUsuarios.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsuariosClient(EndpointConfiguration endpointConfiguration) : 
                base(UsuariosClient.GetBindingForEndpoint(endpointConfiguration), UsuariosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsuariosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UsuariosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsuariosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UsuariosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceUsuarioReference.Usuarios>> GetUsuariosAsync()
        {
            return base.Channel.GetUsuariosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceUsuarioReference.Usuarios> GetUsuarioAsync(int id)
        {
            return base.Channel.GetUsuarioAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> SetUsuarioAsync(string Nombre, System.DateTime Nacimiento, string Sexo)
        {
            return base.Channel.SetUsuarioAsync(Nombre, Nacimiento, Sexo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUsuarioAsync(int id, string Nombre, System.DateTime Nacimiento, string Sexo)
        {
            return base.Channel.UpdateUsuarioAsync(id, Nombre, Nacimiento, Sexo);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveUsuarioAsync(int id)
        {
            return base.Channel.RemoveUsuarioAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsuarios))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsuarios))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64864/Usuarios.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UsuariosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUsuarios);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UsuariosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUsuarios);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUsuarios,
        }
    }
}
